:warning-caption: :warning:

= drugTracker2

== About

The goal of the program is to keep track of pills. +
I made this for myself, as I have to take medicine everyday,
but have a rotating sleep cycle.

What does it actually do?

- Writes down the date and name of a pill that is taken
- Lists past entries using relative and absolute time
- Stores data in a simple csv file, using the XDG Base Directory Specification

[WARNING]
====

This program is new and experimental. I'm also inexperienced as a developer.
A bug in the time handling could exist, leading to wrong
dates being displayed.

The timestamps in this program should be used with caution, as a rough guideline.
Some medicine can require precise timing to be safe. Relying fully on this program could be dangerous. Use common sense.

====

== Installing

=== NixOS (flakes)

Add an input like this to flake.nix
```nix
drugtracker2 = {
  url = "github:saygo-png/drugTracker2";
  inputs.nixpkgs.follows = "nixpkgs";
};
```

Add this to your configuration.nix
```nix
environment.systemPackages = [
  inputs.drugtracker2.packages.${pkgs.system}.drug
];
```

== Building

The main way of building the project is through `nix build`.

`cabal build` can be used, but mileage in building
may vary as the dependencies there are not locked.

== Contributing

`nix fmt` to format all files.

`nix shell` to jump into a shell with `drug` available.
The non flake `nix-shell` is also supported
