name: build

on:
  pull_request:
    paths-ignore:
      - "**.md"
      - ".gitignore"
      - "LICENSE"
jobs:
  treefmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: DeterminateSystems/determinate-nix-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Build program
        run: nix build --accept-flake-config --print-build-logs
